Repository Adapcon/adapcon-utils-js, pull requests merged in 2021-12, with the labels that each got.

#31 feat: added cpf validator
  __tests__/cpfCnpj/utils/index.test.ts
  __tests__/cpfCnpj/validators/index.test.ts
  package.json
  src/cpfCnpj/utils/index.ts
  src/cpfCnpj/validators/index.ts
Labels: enhancement

#32 Integrate Changes
  __tests__/cpfCnpj/utils/index.test.ts
  __tests__/cpfCnpj/validators/index.test.ts
  package.json
  src/cpfCnpj/utils/index.ts
  src/cpfCnpj/validators/index.ts
Labels: merge

#33 feat: add lambdaGetParameters
  __tests__/lambda/lambdaGetParameters.test.ts
  src/lambda/lambdaGetParameters.ts
Labels: enhancement

#35 feat: add constants
  jest.config.js
  src/constants/index.ts
  src/constants/messages.ts
  src/constants/statuses.ts
Labels: enhancement

#34 feat: add lambdaCheckParameters
  __tests__/lambda/lambdaCheckParameters.test.ts
  src/lambda/interfaces.ts
  src/lambda/lambdaCheckParameters.ts
Labels: enhancement

#37 fix: moved aws-lambda to dependency
  package-lock.json
  package.json
Labels: bug

#38 Integrate Changes
  jest.config.js
  package-lock.json
  package.json
  src/constants/index.ts
  src/constants/messages.ts
  src/constants/statuses.ts
Labels: merge

#36 Feat/reorganize lambda responses
  __tests__/lambda/formatters.test.ts
  __tests__/lambda/lambdaResponses.test.ts
  src/lambda/formatters.ts
  src/lambda/index.ts
  src/lambda/interfaces.ts
  src/lambda/lambdaResponses.ts
Labels: enhancement

#39 feat: import functions from index
  __tests__/lambda/lambdaCheckParameters.test.ts
  __tests__/lambda/lambdaGetParameters.test.ts
Labels: enhancement

#42 Chore/reorganizing-string-folder
  __tests__/string/formatters.test.ts
  __tests__/string/validators.test.ts
  src/string/formatters.ts
  src/string/validators.ts
Labels: enhancement

#40 chore: reorganizing date folder
  __tests__/date/date.test.ts
  src/date/date.ts
  src/date/enums.ts
  src/date/index.ts
  src/date/interfaces.ts
Labels: enhancement

#43 Chore/reorganizing phone folder
  __tests__/phone/formatters.test.ts
  src/phone/formatters.ts
Labels: enhancement

#41 chore: reorganizing cpfcnpj folder
  __tests__/cpfCnpj/formatters.test.ts
  __tests__/cpfCnpj/utils.test.ts
  __tests__/cpfCnpj/validators.test.ts
  src/cpfCnpj/formatters.ts
  src/cpfCnpj/utils.ts
  src/cpfCnpj/validators.ts
Labels: enhancement

#44 Chore/reorganizing object folder
  __tests__/object/index.test.ts
  src/object/index.ts
Labels: enhancement

#45 Chore/reorganizing number folder
  __tests__/number/index.test.ts
Labels: enhancement

#46 Feat/add lambda handlers
  __tests__/lambda/formatters.test.ts
  __tests__/lambda/lambdaCheckParameters.test.ts
  __tests__/lambda/lambdaGetParameters.test.ts
  __tests__/lambda/lambdaResponses.test.ts
  src/lambda/formatters.ts
  src/lambda/index.ts
  src/lambda/interfaces.ts
  src/lambda/lambdaCheckParameters.ts
  src/lambda/lambdaGetParameters.ts
  src/lambda/lambdaResponses.ts
Labels: enhancement

#47 chore: reorganizing error folder
  src/error/index.ts
Labels: enhancement

#49 Chore/reorganizing email folder
  __tests__/email/index.test.ts
  __tests__/lambda/lambdaCheckParameters.test.ts
  src/email/awsSES.ts
  src/email/index.ts
  src/email/templates.ts
  src/lambda/lambdaCheckParameters.ts
Labels: enhancement

#48 Chore/reorganizing dao folder
  src/dao/dynamo.ts
  src/dao/dynamo/index.ts
  src/dao/index.ts
  src/dao/interfaces.ts
Labels: enhancement

#52 Feature/created new kebab case to camel case formatter
  __tests__/string/formatters.test.ts
  src/string/formatters.ts
Labels: enhancement

#51 Fix/lambda get parameters parameters
  __tests__/lambda/lambdaGetParameters.test.ts
  src/lambda/lambdaGetParameters.ts
  src/string/formatters.ts
Labels: enhancement
