Repository Adapcon/adapcon-utils-js, pull requests merged in 2022-03, with the labels that each got.

#107 [REFACT] - lambda service invoke function
  package-lock.json
  package.json
  src/lambda/interfaces.ts
  src/lambda/lambdaService.ts
Labels: enhancement

#109 Integrate Changes
  package-lock.json
  package.json
  src/lambda/interfaces.ts
  src/lambda/lambdaService.ts
Labels: merge

#110 [REFACT]: reorganizing functions
  jest.config.js
  package-lock.json
  package.json
  src/lambda/interfaces.ts
  src/lambda/lambdaService.ts
  src/secretsManager/index.ts
  src/secretsManager/interfaces.ts
  src/secretsManager/secretManager.ts
Labels: enhancement

#113 fix: validate isOffline param in SecretManager
  package-lock.json
  package.json
  src/secretsManager/interfaces.ts
  src/secretsManager/secretManager.ts
Labels: bug

#119 Feature/add email validators
  .vscode/settings.json
  __tests__/email/formatters.test.ts
  __tests__/email/validators.test.ts
  package-lock.json
  package.json
  src/email/formatters.ts
  src/email/index.ts
  src/email/validators.ts
Labels: enhancement

#120 Integrate changes
  .vscode/settings.json
  __tests__/email/formatters.test.ts
  __tests__/email/validators.test.ts
  package-lock.json
  package.json
  src/email/formatters.ts
  src/email/index.ts
  src/email/validators.ts
Labels: merge

#123 feat: add codeowners
  .github/CODEOWNERS
Labels: ci

#124 Fix/prisma remove fixed jsondata
  __tests__/prisma/prisma.test.ts
  package-lock.json
  package.json
  src/prisma/prisma.ts
Labels: bug
