Repository Adapcon/adapcon-utils-js, pull requests merged in 2022-02, with the labels that each got.

#74 fix: add prisma keys input params
  src/prisma/prisma.ts
Labels: bug

#75 chore: update to 0.0.30
  package.json
Labels: enhancement

#76 Integrate Changes
  __tests__/lambda/crudHandler.test.ts
  package.json
  src/lambda/crudHandler.ts
  src/prisma/prisma.ts
Labels: merge

#77 Feature/prisma keys manipulation
  __tests__/prisma/prisma.test.ts
  package-lock.json
  package.json
  src/prisma/interfaces.ts
  src/prisma/prisma.ts
Labels: enhancement

#80 Feat/create crud input params and fix existing funcs
  package.json
  src/lambda/crudHandler.ts
  src/lambda/interfaces.ts
  src/prisma/interfaces.ts
  src/prisma/prisma.ts
Labels: enhancement

#82 Integrate Changes
  __tests__/prisma/prisma.test.ts
  package.json
  src/lambda/crudHandler.ts
  src/lambda/interfaces.ts
  src/prisma/interfaces.ts
  src/prisma/prisma.ts
Labels: merge

#83 Fix Lambda invok parameters interface
  package-lock.json
  package.json
  src/lambda/interfaces.ts
Labels: bug

#86 feat: add index file and interfaces/types
  package-lock.json
  package.json
  src/dynamoose/index.ts
  src/dynamoose/interfaces.ts
  src/index.ts
Labels: enhancement

#85 refactor(prisma): export `formatEntitiesKeys`
  package-lock.json
  package.json
  src/prisma/prisma.ts
Labels: enhancement

#87 Integrate Changes
  package-lock.json
  package.json
  src/dynamoose/index.ts
  src/dynamoose/interfaces.ts
  src/index.ts
  src/prisma/prisma.ts
Labels: enhancement

#88 Feat/add dynamoose functions
  __tests__/dynamoose/dynamoose.test.ts
  package-lock.json
  package.json
  src/dynamoose/dynamoose.ts
  src/dynamoose/index.ts
  src/dynamoose/interfaces.ts
Labels: enhancement

#89 Integrate Changes
  __tests__/dynamoose/dynamoose.test.ts
  package-lock.json
  package.json
  src/dynamoose/dynamoose.ts
  src/dynamoose/index.ts
  src/dynamoose/interfaces.ts
Labels: merge

#92 feat: add new key to lambdaParams interface
  package-lock.json
  package.json
  src/lambda/interfaces.ts
Labels: enhancement

#93 Integrate Changes
  package-lock.json
  package.json
  src/lambda/interfaces.ts
Labels: merge

#94 feat: add httpMethod in executeInvoke func
  package-lock.json
  package.json
  src/lambda/lambdaService.ts
Labels: enhancement

#95 Integrate Changes
  package-lock.json
  package.json
  src/lambda/lambdaService.ts
Labels: merge

#99 [FEAT] - validates only count header prop
  __tests__/lambda/crudHandler.test.ts
  package-lock.json
  package.json
  src/lambda/crudHandler.ts
  src/lambda/lambdaGetParameters.ts
Labels: enhancement

#105 feat: add removeSpecialCharacters function
  __tests__/string/formatters.test.ts
  package.json
  src/string/formatters.ts
Labels: enhancement
