Repository Adapcon/adapcon-utils-js, pull requests merged in 2022-04, with the labels that each got.

#126 [FEAT] - create function to switch variables codes to variables values
  __tests__/string/formatters.test.ts
  package-lock.json
  package.json
  src/string/formatters.ts
Labels: enhancement

#127 Integrate Changes
  __tests__/string/formatters.test.ts
  package-lock.json
  package.json
  src/string/formatters.ts
Labels: merge

#128 [FIX] - [BS-26] enable body to be a stringfied json
  package-lock.json
  package.json
  src/lambda/interfaces.ts
Labels: bug

#130 fix: add dynamodb param
  package-lock.json
  package.json
  src/dao/interfaces.ts
Labels: enhancement

#131 fix/add-dynamodbparam (#130)
  package-lock.json
  package.json
  src/dao/interfaces.ts
Labels: merge

#133 fix/add-new-param (#132)
  package-lock.json
  package.json
  src/dao/interfaces.ts
Labels: enhancement, merge

#135 Integrate Changes
  package-lock.json
  package.json
  src/lambda/interfaces.ts
  src/lambda/lambdaService.ts
Labels: merge
