Repository Adapcon/adapcon-utils-js, pull requests merged in 2023-11, with the labels that each got.

#197 feat: adding partial content status code
  package-lock.json
  package.json
  src/http/enums.ts
Labels: enhancement

#198 Integrate Changes
  package-lock.json
  package.json
  src/http/enums.ts
Labels: merge

#199 [FIX] lambda get parameters
  __tests__/lambda/lambdaGetParameters.test.ts
  package-lock.json
  package.json
  src/lambda/lambdaGetParameters.ts
Labels: bug

#200 Integrate Changes
  __tests__/lambda/lambdaGetParameters.test.ts
  package-lock.json
  package.json
  src/lambda/lambdaGetParameters.ts
Labels: merge
