Repository Adapcon/adapcon-utils-js, pull requests merged in 2024-04, with the labels that each got.

#243 feat: unmarshall items on scan result
  package-lock.json
  package.json
  src/dao/dynamo/dao.ts
  src/dao/dynamo/types.ts
Labels: enhancement

#244 Integrate Changes
  package-lock.json
  package.json
  src/dao/dynamo/dao.ts
  src/dao/dynamo/types.ts
Labels: merge

#249 Added s3 response formatter
  package-lock.json
  package.json
  src/s3/formatters.ts
Labels: enhancement

#250 Integrate Changes
  package-lock.json
  package.json
  src/s3/formatters.ts
Labels: merge

#253 Integrate Changes
  __tests__/s3/formatters.test.ts
  package-lock.json
  package.json
  src/lambda/interfaces.ts
  src/lambda/lambdaGetParameters.ts
  src/s3/formatters.ts
  src/s3/index.ts
Labels: merge

#254 [FIX] Bug na hora de extrair parametros do event
  package-lock.json
  package.json
  src/lambda/lambdaGetParameters.ts
Labels: bug

#257 Integrate Changes
  package-lock.json
  package.json
  src/lambda/lambdaGetParameters.ts
Labels: bug

#259 Integrate Changes
  package-lock.json
  package.json
  src/dao/dynamo/dao.ts
Labels: merge
