Repository Adapcon/adapcon-utils-js, pull requests merged in 2024-02, with the labels that each got.

#213 [FEAT] Client S3 Service
  jest.config.js
  package-lock.json
  package.json
  src/index.ts
  src/s3/index.ts
  src/s3/s3Service.ts
Labels: enhancement

#215 [FEAT] Scan Command at Dynamo DAO
  package-lock.json
  package.json
  src/dao/dynamo/dao.ts
Labels: enhancement

#224 [FIX] AWS SDK v3
  .vscode/settings.json
  src/dao/dynamo/dao.ts
Labels: bug

#226 fix: change type import from api gateway proxy types
  package-lock.json
  package.json
  src/lambda/crudHandler.ts
  src/lambda/lambdaResponses.ts
Labels: bug

#227 Integrate Changes
  package-lock.json
  package.json
  src/lambda/crudHandler.ts
  src/lambda/lambdaResponses.ts
Labels: merge

#229 Integrate Changes
  package-lock.json
  package.json
  src/dao/dynamo/dao.ts
  src/lambda/lambdaService.ts
Labels: merge
